### ISSUE TITLE
Crash on newer PyQt5 versions

### ISSUE THREAD

**Issue by Axel-Erfurt** [lafrech/qbirthday#17]
Newer versions no longer accept float for position.

```
test@vm-lm-22-c:~$ ~/.local/bin/qbirthday
Traceback (most recent call last):
  File "/home/test/.local/share/pipx/venvs/qbirthday/lib/python3.12/site-packages/qbirthday/mainwindow.py", line 51, in showEvent
    self.move(systray_icon_pos.x() - self.width() / 2, systray_icon_pos.y())
TypeError: arguments did not match any overloaded call:
  move(self, a0: QPoint): argument 1 has unexpected type 'float'
  move(self, ax: int, ay: int): argument 1 has unexpected type 'float'
Abgebrochen (Speicherabzug geschrieben)
```
change mainwindow.py", line 51 to

`self.move(round(systray_icon_pos.x() - self.width() / 2), systray_icon_pos.y())`

Then it works.

**Comment by lafrech** [comment]
This was fixed in 2023 in 85fb21c891f962ca5439054d4fad71c456f4fc15.

**Comment by Axel-Erfurt** [comment]
The man who asked me for help installed it with pip. The bug is still present in the pip version.

**Comment by lafrech** [comment]
Oh, right. I never configured auto-release to PyPI but I'm so used to it on other projects that I haven't manually published for a while. Thanks for the heads up.

I just released latest versions.
